version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bancopan
      - MONGO_INITDB_ROOT_PASSWORD=bancopan
    ports:
      - "27017:27017"   

  redis:
    image: redis
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bancopan
      - MONGO_INITDB_ROOT_PASSWORD=bancopan
    ports:
      - "6379:6379"   